- hosts: all
  remote_user: kohei
  vars:
    - proj_dest: /home/kohei
  tasks:
    - name: "apt-get install"
      apt: pkg={{ item }}
      sudo: yes
      with_items:
        - git  
        - ruby2.3
        - openvswitch-switch
        - libssl-dev
        - sqlite3
        - libsqlite3-dev
        - libxml2-dev
        - libxslt1-dev
        - build-essential
        - patch
        - ruby-dev
        - zlib1g-dev
        - liblzma-dev
        - libgmp-dev


    - name: "nettester"
      git: repo=https://github.com/yasuhito/net_tester.git dest={{proj_dest}}/net_tester version=feature/firewall

    - name: "Install Bundler"
      sudo: yes
      gem: name=bundler version=1.11.2 user_install=False

    - name: "bundle install"
      sudo: yes
      shell: /bin/sh -lc "bundle _1.11.2_ install" chdir={{proj_dest}}/net_tester



